
# Site settings

url: "https://harishkumar101.github.io"

baseurl: 

# Google tracking id

google-tracking-id: ""

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Harish Kumar"
title: "Harish Kumar"
description: "Blog and website of Harish Kumar, blogging mainly for tech. Opinions expressed are mine."
keywords: "kumar, harish, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "../img/intro-bg-1.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "Cool cool cool cool cool no doubt noo doooubt!"
  - text: "Valar Morghulis. Valar Dohaeris."
  - text: "I'm not great at advice, but can I interest you in a sarcastic comment?"
  - text: "Make memes, not war."
  - text: "Squirrel!"
  - text: "By all means move at a glacial pace. You know how that thrills me."
  - text: "The ratio of people to cake is too big."


#me-img: "https://github.com/harishkumar101.png?size=500"
me-img: "https://avatars.githubusercontent.com/u/46072258?v=4.png?size=500"

color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "harish-kumar"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/cisco.png"
    date: "Jan 2021 - Present"
    description: "Software Developer at Cisco Systems"
  - image: "/img/timeline/nxp.png"
    date: "April 2019 - Dec 2020"
    description: "Firmware Developer at NXP Semiconductors"
  - image: "/img/timeline/hello-world.png"
    date: "December 2018"
    description: "Started coding!"  
  - image: "/img/timeline/annauniv.png"
    date: "Jun 2014 - May 2018"
    description: "Engineering student at Anna University"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "harishec031@gmail.com"

################
# Author Blurb #
################

author_blurb: "Harish Kumar is an awesome person. He loves dogs. In his spare time, Harish likes to binge watch shows on Netflix."
author_blurb_image: "/img/harish.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/hgharish"
  - title: "github"
    url: "https://github.com/harishkumar101"
  - title: "wordpress"
    url: "https://harishkumar101.wordpress.com"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: harishkumar
keybase-in-social: False
keybase-in-footer: False

################################################################################

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Projects: 'projects'
  Contact: 'contact'
  
  
# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
